# .travis.yml Execution script for role tests on Travis-CI
---
sudo: required

env:
  matrix:
    - DISTRIBUTION: centos
      VERSION: 7
    - DISTRIBUTION: ubuntu
      VERSION: 18.04
    - DISTRIBUTION: debian
      VERSION: 9
    - DISTRIBUTION: debian
      VERSION: 10
    - DISTRIBUTION: fedora
      VERSION: 29
    - DISTRIBUTION: fedora
      VERSION: 30
services:
  - docker

before_install:
  # Install latest Git
  - sudo apt-get update
  - sudo apt-get install --only-upgrade git
  - sudo apt-get install -y smbclient samba-common-bin
  # Allow fetching other branches than master
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  # Fetch the branch with test code
  - git fetch origin docker-tests
  - git worktree add docker-tests origin/docker-tests

script:
  # Create container, apply test playbook and run tests
  - ./tests/docker-tests.sh
